### ISSUE TITLE
mysqld process won't start when using a data volume

### ISSUE THREAD

**Issue by anweiss** [severalnines/galera-docker-pxc56#1]
When mounting a data volume to `/var/lib/mysql`, I noticed that `mysqld` seems to hang at:

```sh
[Note] mysqld (mysqld 5.6.34-79.1-56) starting as process 38 ...
```

My docker-compose.yml file is as follows:

```yaml
version: '3.1'
 
services:
  etcd:
    deploy:
      replicas: 1
    image: elcolio/etcd:latest
    command: ["-name etcd", "-discovery <my_discovery_endpoint>"]
    volumes:
      - ./etcd_data:/data
    networks:
      - galera_net

  galera:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        max_failure_ratio: 0.3
    image: severalnines/pxc56
    volumes:
      - galera_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      CLUSTER_NAME: "my_wsrep_cluster"
      XTRABACKUP_PASSWORD: "mypassword"
      DISCOVERY_SERVICE: 'etcd:2379'
      MYSQL_DATABASE: 'mydatabase'
    networks:
      - galera_net
 
volumes:
  galera_data:
 
networks:
  galera_net:
    driver: overlay
```
